openapi: 3.0.0
info:
  title: E-Commerce API
  version: 1.0.0
paths:
  /api/v1/products/:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
